#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push dipto007/stockanalytica:latest
curl https://get.okteto.com -sSfL | sh
okteto login --token 96BIdJi1DTGafav9dYtA3Upz2xyefgPy3JgzbWOV
okteto namespace
kubectl apply -f k8s.yml