kind: Deployment
apiVersion: apps/v1
metadata:
  name: stockanalytica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockanalytica
  template:
    metadata:
      labels:
        app: stockanalytica
    spec:
      containers:
        - name: stockanalytica
          image: okteto.dev/stockanalytica
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: stockanalytica
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: stockanalytica